---
# handlers file for EtcdHaproxyServer
# перезапскаем сервис  etcd и мтавим ему возможность автозапуска
- name: restart etcd
  service:
     state: restarted
     daemon_reload: yes
     name: etcd
     enabled: yes
- name: restart haproxy
  service:
     state: restarted
     daemon_reload: yes
     name: haproxy
     enabled: yes

