---
# tasks file for patroni
# Копирования файла конфигурации для кластера beta
- name: Configure Patroni
  copy:
    src: ./files/beta/config.yml
    dest: /etc/patroni
  when: ansible_facts['hostname']=="beta"
