---
# tasks file for patroni
# конфигурация сервера gamma кластера 
- name: Configure Patroni
  copy:
    src: ./files/gamma/config.yml
    dest: /etc/patroni
  when: ansible_facts["hostname"]=="gamma"
