---
# handlers file for patroni
# перезапуск patroni
- name: restarted patroni
  service:
     state: restarted
     daemon_reload: yes
     name: patroni
# копируем конфигурационный фаил для patroni.service
- name: copy "patroni.service file"
- name: Configure Patroni
  copy:
    src: ./files/service/patroni.service
    dest: /lib/systemd/system/patroni.service