---
#Configore psql apt repository
# Добавления ключей репозитория posgresql-11
- name: apt key posgres11
  apt_key:
       url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state: present
- name: add repository
  apt_repository:
       repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
       state: present